export const seedBooks = [
  { id: "seed-1", title: "Atomic Habits", author: "James Clear", category: "Psychology" },
  { id: "seed-2", title: "Deep Work", author: "Cal Newport", category: "Strategy" },
  { id: "seed-3", title: "The 7 Habits of Highly Effective People", author: "Stephen Covey", category: "Leadership" },
  { id: "seed-4", title: "Thinking, Fast and Slow", author: "Daniel Kahneman", category: "Psychology" },
  { id: "seed-5", title: "The Psychology of Money", author: "Morgan Housel", category: "Finance" },
  { id: "seed-6", title: "Man's Search for Meaning", author: "Viktor Frankl", category: "Philosophy" },
  { id: "seed-7", title: "Start with Why", author: "Simon Sinek", category: "Leadership" },
  { id: "seed-8", title: "Measure What Matters", author: "John Doerr", category: "Strategy" },
  { id: "seed-9", title: "Essentialism", author: "Greg McKeown", category: "Psychology" },
  { id: "seed-10", title: "The Lean Startup", author: "Eric Ries", category: "Strategy" },
  { id: "seed-11", title: "Principles", author: "Ray Dalio", category: "Finance" },
  { id: "seed-12", title: "Meditations", author: "Marcus Aurelius", category: "Philosophy" },
  { id: "seed-13", title: "Leaders Eat Last", author: "Simon Sinek", category: "Leadership" },
  { id: "seed-14", title: "The Almanack of Naval Ravikant", author: "Eric Jorgenson", category: "Finance" },
  { id: "seed-15", title: "The Effective Executive", author: "Peter Drucker", category: "Leadership" },
  { id: "seed-16", title: "The Daily Stoic", author: "Ryan Holiday", category: "Philosophy" },
  { id: "seed-17", title: "Good Strategy Bad Strategy", author: "Richard Rumelt", category: "Strategy" },
];
